#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Registra las dependencias instaladas por Composer desde la raíz del proyecto.
require __DIR__.'/vendor/autoload.php';

// Inicializa Laravel y delega la ejecución del comando a la aplicación.
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
