#!/usr/bin/env php
<?php

use Illuminate\Foundation\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (file_exists(__DIR__.'/../vendor/autoload.php')) {
    require __DIR__.'/../vendor/autoload.php';
} else {
    require __DIR__.'/../bootstrap/autoload.php';
}

$app = require_once __DIR__.'/../bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);